import { CallRecord } from './callRecordsTypes';

export const INITIAL_CALL_RECORDS: CallRecord[] = [
  {
    id: 'CALL-20260810-093641',
    callInTime: '2026-08-10 09:36:41',
    customerPhone: '13812342687',
    agentName: '保通保险客服专员',
    agentId: 'h_insure',
    location: '北京',
    duration: '04分26秒',
    durationSeconds: 266,
    rounds: 5,
    hangupParty: '客户挂断',
    tags: ['配送预约', '日期确认', '高意向'],
    llmLabel: '预约确认成功',
    labelDetail: {
      ruleName: '客户配送预约与时间二次确认闭环判定',
      modelName: '京小灵-大模型意图判定引擎 v3.2',
      confidence: 0.986,
      matchedIntent: '配送预约确认闭环',
      triggerReason: '客户在第4轮明确提出“师傅明天上午10点能准时送到吗？”，数字员工回复确认并提醒保持畅通，客户肯定后正常结束通话。',
      conditions: [
        { title: '关键词意图识别', matched: true, detail: '匹配到核心词组：预约、师傅、明天上午、准时送、家里有人' },
        { title: '大模型语义置信度', matched: true, detail: '语义相似度得分 0.986，远超标准阈值 0.85' },
        { title: '流程关键节点闭环', matched: true, detail: '进入并完整完成【开始流程-普通节点】与【预约确认节点】' },
        { title: '负向情绪过滤', matched: true, detail: '未检测到投诉、拒收或转人工诉求' },
      ],
    },
    metrics: {
      aiSpeechRatio: '61.40%',
      aiSpeechRatioNum: 61.4,
      longestCustomerNarrative: '2.1秒',
      longestAiMonologue: '3.3秒',
      totalRounds: 5,
    },
    sessionRemark: '双击编辑备注',
    utterances: [
      {
        id: 'utt_01',
        sender: 'ai',
        speakerName: '数字员工',
        text: '祝您生活愉快，再见。祝您生活愉快，再见。祝您生活愉快，再见。祝您生活愉快，再见。祝您生活愉快，再见。',
        timestamp: '09:36:42',
        nodeName: '来自：开始流程-普通节点',
        nonInterruptSeconds: 0,
        audioDurationSeconds: 3.3,
      },
      {
        id: 'utt_02',
        sender: 'customer',
        speakerName: '客户',
        text: '停停停停停停',
        timestamp: '09:36:47',
        audioDurationSeconds: 1.2,
      },
      {
        id: 'utt_03',
        sender: 'ai',
        speakerName: '数字员工',
        text: '12345678912345678123456789',
        timestamp: '09:36:50',
        nodeName: '来自：开始流程-普通节点',
        nonInterruptSeconds: 0,
        audioDurationSeconds: 2.5,
      },
      {
        id: 'utt_04',
        sender: 'customer',
        speakerName: '客户',
        text: '师傅明天上午10点能准时送到吗？家里有人。',
        timestamp: '09:36:55',
        audioDurationSeconds: 2.1,
      },
      {
        id: 'utt_05',
        sender: 'ai',
        speakerName: '数字员工',
        text: '好的，已为您成功登记预约配送时间为明日上午10:00，京东快递小哥派件前会提前与您电话核对，请保持手机畅通！',
        timestamp: '09:37:00',
        nodeName: '来自：开始流程-普通节点',
        nonInterruptSeconds: 0,
        audioDurationSeconds: 3.1,
      },
    ],
  },
  {
    id: 'CALL-20260810-091702',
    callInTime: '2026-08-10 09:17:02',
    customerPhone: '18823719812',
    agentName: '商城售后客服',
    agentId: 'h_mall',
    location: '广东深圳',
    duration: '02分15秒',
    durationSeconds: 135,
    rounds: 3,
    hangupParty: '坐席挂断',
    tags: ['故障配送', '急需加急'],
    llmLabel: '工单已催派',
    labelDetail: {
      ruleName: '异常配送包裹加急核查标准',
      modelName: '京小灵-大模型意图判定引擎 v3.2',
      confidence: 0.965,
      matchedIntent: '配送停滞催办',
      triggerReason: '客户反馈物流节点24小时无更新，AI调取运单API后完成在线工单催发。',
      conditions: [
        { title: '单号识别', matched: true, detail: '自动提取顺丰运单号 SF190028198' },
        { title: '催单链路触发', matched: true, detail: '触发工单系统并下发催派指令' },
      ],
    },
    metrics: {
      aiSpeechRatio: '54.20%',
      aiSpeechRatioNum: 54.2,
      longestCustomerNarrative: '4.5秒',
      longestAiMonologue: '2.8秒',
      totalRounds: 3,
    },
    sessionRemark: '客户情绪略显焦虑，已由工单组加急跟进处理',
    utterances: [
      {
        id: 'utt_11',
        sender: 'ai',
        speakerName: '数字员工',
        text: '您好，这里是京东商城售后客服专线，请问有什么可以帮您？',
        timestamp: '09:17:03',
        nodeName: '来自：流程接待-开场节点',
        nonInterruptSeconds: 0,
        audioDurationSeconds: 2.2,
      },
      {
        id: 'utt_12',
        sender: 'customer',
        speakerName: '客户',
        text: '我买的生鲜包裹在转运中心卡了一天了，再不送过来就要坏掉了，能帮我加急派送吗？',
        timestamp: '09:17:08',
        audioDurationSeconds: 4.5,
      },
      {
        id: 'utt_13',
        sender: 'ai',
        speakerName: '数字员工',
        text: '非常抱歉给您带来不便！系统已为您生成物流绿色通道催派工单，所属营业部将在2小时内跟进并优先派送。',
        timestamp: '09:17:15',
        nodeName: '来自：物流协同-加急工单节点',
        nonInterruptSeconds: 0,
        audioDurationSeconds: 2.8,
      },
    ],
  },
  {
    id: 'CALL-20260810-085310',
    callInTime: '2026-08-10 08:53:10',
    customerPhone: '15099881120',
    agentName: '家电技术支持专员',
    agentId: 'h_tech',
    location: '上海',
    duration: '03分40秒',
    durationSeconds: 220,
    rounds: 6,
    hangupParty: '数字员工挂断',
    tags: ['冰箱排查', '故障排查'],
    llmLabel: '故障远程排查完成',
    labelDetail: {
      ruleName: '制冷家电远程温控诊断与复位指南',
      modelName: '京小灵-大模型意图判定引擎 v3.2',
      confidence: 0.978,
      matchedIntent: '温控传感器及门封排查',
      triggerReason: '引导用户完成门封磁吸检查与变频温控复位，故障声音已消失。',
      conditions: [
        { title: '故障症状归类', matched: true, detail: '冷藏室结冰与风道异响' },
        { title: '远程排查操作达成', matched: true, detail: '用户反馈断电重启后显示屏报错代码已清除' },
      ],
    },
    metrics: {
      aiSpeechRatio: '58.80%',
      aiSpeechRatioNum: 58.8,
      longestCustomerNarrative: '3.8秒',
      longestAiMonologue: '4.1秒',
      totalRounds: 6,
    },
    sessionRemark: '典型技术远程指导案例，未产生上门售后成本',
    utterances: [
      {
        id: 'utt_21',
        sender: 'ai',
        speakerName: '数字员工',
        text: '您好，家电技术服务中心为您服务，请问您的冰箱遇到了什么问题？',
        timestamp: '08:53:11',
        nodeName: '来自：服务开场-故障初筛',
        nonInterruptSeconds: 0,
        audioDurationSeconds: 2.8,
      },
      {
        id: 'utt_22',
        sender: 'customer',
        speakerName: '客户',
        text: '我家双开门冰箱这几天冷藏室老是嗡嗡响，温度还显示升高了。',
        timestamp: '08:53:16',
        audioDurationSeconds: 3.8,
      },
      {
        id: 'utt_23',
        sender: 'ai',
        speakerName: '数字员工',
        text: '您可以先检查一下背部散热孔周围是否有遮挡物，另外门封条是否有漏气现象呢？',
        timestamp: '08:53:22',
        nodeName: '来自：排查指引-外观风道',
        nonInterruptSeconds: 0,
        audioDurationSeconds: 3.6,
      },
      {
        id: 'utt_24',
        sender: 'customer',
        speakerName: '客户',
        text: '我刚把旁边的纸箱拿开了，好像是贴太近了。',
        timestamp: '08:53:30',
        audioDurationSeconds: 2.5,
      },
      {
        id: 'utt_25',
        sender: 'ai',
        speakerName: '数字员工',
        text: '太好了！请您观察10分钟，如果声音未恢复，可长按冷藏按键3秒进行智能系统自检。',
        timestamp: '08:53:35',
        nodeName: '来自：排查指引-自检复位',
        nonInterruptSeconds: 0,
        audioDurationSeconds: 4.1,
      },
      {
        id: 'utt_26',
        sender: 'customer',
        speakerName: '客户',
        text: '明白，谢谢你，我先试试看。',
        timestamp: '08:53:42',
        audioDurationSeconds: 1.8,
      },
    ],
  },
  {
    id: 'CALL-20260809-213010',
    callInTime: '2026-08-09 21:30:10',
    customerPhone: '13712399880',
    agentName: '发票开具服务助手',
    agentId: 'h_invoice',
    location: '浙江杭州',
    duration: '01分48秒',
    durationSeconds: 108,
    rounds: 2,
    hangupParty: '客户挂断',
    tags: ['发票开具', '专票申请'],
    llmLabel: '发票抬头已推送',
    labelDetail: {
      ruleName: '增值税电子专用发票自动开具',
      modelName: '京小灵-大模型意图判定引擎 v3.2',
      confidence: 0.992,
      matchedIntent: '企业专票申请',
      triggerReason: '确认企业税号及订单信息无误，发票开具链接已直接短信推送。',
      conditions: [
        { title: '企业税号校验', matched: true, detail: '符合标准18位统一社会信用代码规范' },
        { title: '合规验证', matched: true, detail: '订单已完成收货且未逾开票期限' },
      ],
    },
    metrics: {
      aiSpeechRatio: '48.30%',
      aiSpeechRatioNum: 48.3,
      longestCustomerNarrative: '3.0秒',
      longestAiMonologue: '2.5秒',
      totalRounds: 2,
    },
    sessionRemark: '客户对短信直发电子专票功能表示满意',
    utterances: [
      {
        id: 'utt_31',
        sender: 'ai',
        speakerName: '数字员工',
        text: '您好，发票开具服务专员为您服务。请问需要开具哪笔订单的发票？',
        timestamp: '21:30:11',
        nodeName: '来自：财务服务-开票识别',
        nonInterruptSeconds: 0,
        audioDurationSeconds: 2.5,
      },
      {
        id: 'utt_32',
        sender: 'customer',
        speakerName: '客户',
        text: '我刚才买的办公电脑，需要开增值税专用发票，税号发哪里？',
        timestamp: '21:30:16',
        audioDurationSeconds: 3.0,
      },
      {
        id: 'utt_33',
        sender: 'ai',
        speakerName: '数字员工',
        text: '已为您通过短信发送安全开票链接，您点击后可直接一键导入企业开票信息，系统将自动核验并开具。',
        timestamp: '21:30:22',
        nodeName: '来自：财务服务-链接下发',
        nonInterruptSeconds: 0,
        audioDurationSeconds: 2.5,
      },
    ],
  },
  {
    id: 'CALL-20260809-182412',
    callInTime: '2026-08-09 18:24:12',
    customerPhone: '13500787750',
    agentName: '企业采购服务专员',
    agentId: 'h_procure',
    location: '江苏南京',
    duration: '05分12秒',
    durationSeconds: 312,
    rounds: 7,
    hangupParty: '客户挂断',
    tags: ['企业采购', '批量意向', '高意向'],
    llmLabel: '大客户方案待跟进',
    labelDetail: {
      ruleName: '大宗采购意向商机自动评级与分发',
      modelName: '京小灵-大模型意图判定引擎 v3.2',
      confidence: 0.954,
      matchedIntent: '批量采购意向',
      triggerReason: '采购数量超 200 台，预算等级 A 级，系统自动触发大客户专属经理对接。',
      conditions: [
        { title: '品类匹配', matched: true, detail: '企业级办公显示器与主机批量采购' },
        { title: '采购规模判定', matched: true, detail: '采购量 > 100 台，金额预估 > 50 万元' },
      ],
    },
    metrics: {
      aiSpeechRatio: '64.70%',
      aiSpeechRatioNum: 64.7,
      longestCustomerNarrative: '5.2秒',
      longestAiMonologue: '4.5秒',
      totalRounds: 7,
    },
    sessionRemark: '已同步推送企业采购 KA 专员电话回访',
    utterances: [
      {
        id: 'utt_41',
        sender: 'ai',
        speakerName: '数字员工',
        text: '您好，这里是企业采购大客户服务中心，请问贵司本次的采购意向包括哪些品类？',
        timestamp: '18:24:13',
        nodeName: '来自：企业KA-意向问询',
        nonInterruptSeconds: 0,
        audioDurationSeconds: 3.5,
      },
      {
        id: 'utt_42',
        sender: 'customer',
        speakerName: '客户',
        text: '我们准备为新职场采购两百多套办公电脑和人体工学椅，想了解下有没有阶梯团购折扣？',
        timestamp: '18:24:20',
        audioDurationSeconds: 5.2,
      },
      {
        id: 'utt_43',
        sender: 'ai',
        speakerName: '数字员工',
        text: '完全支持！针对两百套以上的集中采购，我们提供企业专属折扣、账期结算以及免费上门组装服务。我已为您生成专享报价单草案。',
        timestamp: '18:24:30',
        nodeName: '来自：企业KA-方案介绍',
        nonInterruptSeconds: 0,
        audioDurationSeconds: 4.5,
      },
    ],
  },
  {
    id: 'CALL-20260809-150821',
    callInTime: '2026-08-09 15:08:21',
    customerPhone: '13890881234',
    agentName: '京东物流配送专员',
    agentId: 'h_logistics',
    location: '四川成都',
    duration: '01分25秒',
    durationSeconds: 85,
    rounds: 2,
    hangupParty: '系统挂断',
    tags: ['配送预约', '超时未应答'],
    llmLabel: '系统超时自动流转',
    labelDetail: {
      ruleName: '呼叫静音与无应答智能处置规则',
      modelName: '京小灵-大模型意图判定引擎 v3.2',
      confidence: 0.941,
      matchedIntent: '静音超时挂断',
      triggerReason: '两次澄清播报后均检测到背景静音超 15 秒，系统执行合规挂断。',
      conditions: [
        { title: 'VAD静音检测', matched: true, detail: '首轮静音时长 15.2 秒，二次提醒后仍无音频输入' },
      ],
    },
    metrics: {
      aiSpeechRatio: '72.10%',
      aiSpeechRatioNum: 72.1,
      longestCustomerNarrative: '1.2秒',
      longestAiMonologue: '3.8秒',
      totalRounds: 2,
    },
    sessionRemark: '客户可能误触呼入，未产生实质沟通',
    utterances: [
      {
        id: 'utt_51',
        sender: 'ai',
        speakerName: '数字员工',
        text: '您好，京东快递竭诚为您服务，请问有什么可以帮您？',
        timestamp: '15:08:22',
        nodeName: '来自：物流服务-通用接通',
        nonInterruptSeconds: 0,
        audioDurationSeconds: 2.4,
      },
      {
        id: 'utt_52',
        sender: 'customer',
        speakerName: '客户',
        text: '喂……喂？',
        timestamp: '15:08:28',
        audioDurationSeconds: 1.2,
      },
      {
        id: 'utt_53',
        sender: 'ai',
        speakerName: '数字员工',
        text: '您好，我听得见您的声音。请问您需要查询包裹还是预约寄件呢？',
        timestamp: '15:08:32',
        nodeName: '来自：物流服务-静音提示',
        nonInterruptSeconds: 0,
        audioDurationSeconds: 3.8,
      },
    ],
  },
  {
    id: 'CALL-20260809-141209',
    callInTime: '2026-08-09 14:12:09',
    customerPhone: '18511002233',
    agentName: '家电技术支持专员',
    agentId: 'h_tech',
    location: '山东青岛',
    duration: '03分10秒',
    durationSeconds: 190,
    rounds: 4,
    hangupParty: '客户挂断',
    tags: ['冰箱排查', '耗电咨询'],
    llmLabel: '节能指引完成',
    labelDetail: {
      ruleName: '家用电器能耗与使用保养问答',
      modelName: '京小灵-大模型意图判定引擎 v3.2',
      confidence: 0.962,
      matchedIntent: '耗电偏高解答',
      triggerReason: '解答新一级能效标准与夏季高温环境散热功率变化，客户表示已理解。',
      conditions: [
        { title: '知识库匹配', matched: true, detail: '命中知识条目《夏季电冰箱节能使用十问十答》' },
      ],
    },
    metrics: {
      aiSpeechRatio: '52.60%',
      aiSpeechRatioNum: 52.6,
      longestCustomerNarrative: '3.4秒',
      longestAiMonologue: '3.1秒',
      totalRounds: 4,
    },
    sessionRemark: '客户对能效说明解答表示认可',
    utterances: [
      {
        id: 'utt_61',
        sender: 'ai',
        speakerName: '数字员工',
        text: '您好，家电技术客服为您服务，请问有什么家电使用疑问？',
        timestamp: '14:12:10',
        nodeName: '来自：技术服务-通用问答',
        nonInterruptSeconds: 0,
        audioDurationSeconds: 2.6,
      },
      {
        id: 'utt_62',
        sender: 'customer',
        speakerName: '客户',
        text: '新买的冰箱我看这几天电表走得挺快的，一级能效是不是虚标啊？',
        timestamp: '14:12:16',
        audioDurationSeconds: 3.4,
      },
      {
        id: 'utt_63',
        sender: 'ai',
        speakerName: '数字员工',
        text: '新机初次通电24小时内，压缩机会持续高频运转以快速达到设定低温，后续进入恒温期后耗电量会显著下降至标称日均0.8度左右。',
        timestamp: '14:12:22',
        nodeName: '来自：技术服务-知识库解答',
        nonInterruptSeconds: 0,
        audioDurationSeconds: 3.1,
      },
    ],
  },
  {
    id: 'CALL-20260809-110844',
    callInTime: '2026-08-09 11:08:44',
    customerPhone: '18900128900',
    agentName: '商城售后客服',
    agentId: 'h_mall',
    location: '湖北武汉',
    duration: '02分45秒',
    durationSeconds: 165,
    rounds: 4,
    hangupParty: '数字员工挂断',
    tags: ['发票开具', '电子凭证'],
    llmLabel: '电子发票已发送',
    labelDetail: {
      ruleName: '个人电子普通发票自动推送流程',
      modelName: '京小灵-大模型意图判定引擎 v3.2',
      confidence: 0.989,
      matchedIntent: '电子发票下载',
      triggerReason: '已将 PDF 电子普通发票推送至用户注册绑定的电子邮箱。',
      conditions: [
        { title: '发票开具状态', matched: true, detail: '税务系统已成功返回发票代码与查验码' },
      ],
    },
    metrics: {
      aiSpeechRatio: '59.00%',
      aiSpeechRatioNum: 59.0,
      longestCustomerNarrative: '2.6秒',
      longestAiMonologue: '3.0秒',
      totalRounds: 4,
    },
    sessionRemark: '发票服务自助流转顺畅',
    utterances: [
      {
        id: 'utt_71',
        sender: 'ai',
        speakerName: '数字员工',
        text: '您好，这里是京东商城客户服务，请问需要办理什么售后业务？',
        timestamp: '11:08:45',
        nodeName: '来自：商城客服-业务分流',
        nonInterruptSeconds: 0,
        audioDurationSeconds: 2.7,
      },
      {
        id: 'utt_72',
        sender: 'customer',
        speakerName: '客户',
        text: '我上周买的运动鞋需要报销，麻烦把电子发票发我邮箱一下。',
        timestamp: '11:08:50',
        audioDurationSeconds: 2.6,
      },
      {
        id: 'utt_73',
        sender: 'ai',
        speakerName: '数字员工',
        text: '已为您查询到该笔订单，发票 PDF 原件已成功发送至您的尾号 8900 的安全邮箱，请注意查收！',
        timestamp: '11:08:55',
        nodeName: '来自：商城客服-邮件直发',
        nonInterruptSeconds: 0,
        audioDurationSeconds: 3.0,
      },
    ],
  },
];
